from __future__ import annotations

import hashlib
import os
import shutil
from pathlib import Path

from PIL import Image

from app.i18n import default_project_name
from app.models import StoryProject, default_scene
from app.utils import load_json, save_json


IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp"}
AUDIO_EXTENSIONS = {".wav", ".mp3", ".ogg", ".m4a"}


def new_project(name: str | None = None, grid_rows: int | None = None, grid_cols: int | None = None) -> StoryProject:
    project = StoryProject(project_name=name or default_project_name(), scenes=[default_scene(1, grid_rows, grid_cols)], initial_scene_id="scene_1")
    if grid_rows and grid_cols:
        project.grid_rows = int(grid_rows)
        project.grid_cols = int(grid_cols)
    return project


def _project_assets_root(project_path: str) -> Path:
    target = Path(project_path)
    return target.parent / f"{target.stem}_assets"


def _sanitize_name(name: str) -> str:
    safe = "".join(ch if ch.isalnum() or ch in {"-", "_", "."} else "_" for ch in (name or ""))
    return safe or "asset"


def _file_sha1(path: Path) -> str:
    hasher = hashlib.sha1()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


def _find_existing_identical_asset(src: Path, dest_dir: Path) -> Path | None:
    if not dest_dir.exists():
        return None
    src_hash = _file_sha1(src)
    for candidate in dest_dir.iterdir():
        if not candidate.is_file():
            continue
        if candidate.suffix.lower() != src.suffix.lower():
            continue
        try:
            if _file_sha1(candidate) == src_hash:
                return candidate
        except Exception:
            continue
    return None


def _copy_asset_for_project(asset_path: str, project_path: str, bucket: str) -> str:
    asset_path = (asset_path or "").strip()
    if not asset_path:
        return ""
    src = Path(asset_path)
    project_file = Path(project_path)
    if not src.is_absolute():
        src = (project_file.parent / src).resolve()
    if not src.exists() or not src.is_file():
        return asset_path

    assets_root = _project_assets_root(project_path).resolve()
    dest_dir = (assets_root / bucket).resolve()
    dest_dir.mkdir(parents=True, exist_ok=True)

    try:
        src_resolved = src.resolve()
    except Exception:
        src_resolved = src

    # If the asset is already inside this project's assets folder, keep it as-is.
    try:
        if src_resolved.is_relative_to(assets_root):
            return os.path.relpath(src_resolved, project_file.parent)
    except Exception:
        pass

    existing_identical = _find_existing_identical_asset(src_resolved, dest_dir)
    if existing_identical is not None:
        return os.path.relpath(existing_identical, project_file.parent)

    base_name = _sanitize_name(src_resolved.name)
    dest = dest_dir / base_name
    if dest.exists() and dest.resolve() != src_resolved.resolve():
        stem = _sanitize_name(src_resolved.stem)
        suffix = src_resolved.suffix.lower()
        counter = 1
        while True:
            candidate = dest_dir / f"{stem}_{counter}{suffix}"
            if not candidate.exists():
                dest = candidate
                break
            try:
                if candidate.is_file() and _file_sha1(candidate) == _file_sha1(src_resolved):
                    dest = candidate
                    break
            except Exception:
                pass
            counter += 1

    if dest.resolve() != src_resolved.resolve():
        shutil.copy2(src_resolved, dest)
    return os.path.relpath(dest, project_file.parent)




def _is_image_path(asset_path: str) -> bool:
    return Path(asset_path or "").suffix.lower() in IMAGE_EXTENSIONS


def _copy_image_for_project(asset_path: str, project_path: str, bucket: str = "images", *, max_side: int = 1400, quality: int = 82) -> str:
    """Copy an image into the project assets folder as an optimized WebP.

    Large PNG/JPEG files generated by AI tools can make Sara projects very
    heavy. This function stores project images in a compact, deterministic
    WebP file while preserving the live in-memory path until save/load.
    """
    asset_path = (asset_path or "").strip()
    if not asset_path:
        return ""
    src = Path(asset_path)
    project_file = Path(project_path)
    if not src.is_absolute():
        src = (project_file.parent / src).resolve()
    if not src.exists() or not src.is_file():
        return asset_path

    assets_root = _project_assets_root(project_path).resolve()
    dest_dir = (assets_root / bucket).resolve()
    dest_dir.mkdir(parents=True, exist_ok=True)

    try:
        src_resolved = src.resolve()
    except Exception:
        src_resolved = src

    # Already optimized inside this project: keep the relative reference.
    try:
        if src_resolved.is_relative_to(assets_root) and src_resolved.suffix.lower() == ".webp":
            return os.path.relpath(src_resolved, project_file.parent)
    except Exception:
        pass

    try:
        digest = _file_sha1(src_resolved)[:12]
    except Exception:
        digest = "image"
    stem = _sanitize_name(src_resolved.stem)
    dest = dest_dir / f"{stem}_{digest}.webp"
    if dest.exists():
        return os.path.relpath(dest, project_file.parent)

    try:
        with Image.open(src_resolved) as img:
            image = img.convert("RGBA")
            if max(image.size) > int(max_side):
                image.thumbnail((int(max_side), int(max_side)), Image.LANCZOS)
            # WebP supports alpha; for opaque images RGB is smaller.
            if image.getbbox() is not None:
                alpha = image.getchannel("A")
                if alpha.getextrema() == (255, 255):
                    image = image.convert("RGB")
            image.save(dest, format="WEBP", quality=int(quality), method=4)
        return os.path.relpath(dest, project_file.parent)
    except Exception:
        # If Pillow cannot process the file, fall back to a normal copy.
        return _copy_asset_for_project(asset_path, project_path, bucket)

def _bucket_for_path(asset_path: str, default_bucket: str) -> str:
    suffix = Path(asset_path or "").suffix.lower()
    if suffix in IMAGE_EXTENSIONS:
        return "images"
    if suffix in AUDIO_EXTENSIONS:
        return "audio"
    return default_bucket


def _prepare_project_assets_for_save(project: StoryProject, project_path: str) -> None:
    for scene in project.scenes:
        scene.background_image = _copy_image_for_project(
            scene.background_image,
            project_path,
            _bucket_for_path(scene.background_image, "images"),
            max_side=1600,
            quality=84,
        )
        scene.scene_audio = _copy_asset_for_project(
            scene.scene_audio,
            project_path,
            _bucket_for_path(scene.scene_audio, "audio"),
        )
        for cell in scene.cells:
            cell.image_path = _copy_image_for_project(
                cell.image_path,
                project_path,
                _bucket_for_path(cell.image_path, "images"),
                max_side=900,
                quality=82,
            )
            cell.audio_path = _copy_asset_for_project(
                cell.audio_path,
                project_path,
                _bucket_for_path(cell.audio_path, "audio"),
            )
        for support in list(getattr(scene, "supports", []) or []):
            support.image_path = _copy_image_for_project(
                support.image_path,
                project_path,
                _bucket_for_path(support.image_path, "images"),
                max_side=900,
                quality=82,
            )
            support.audio_path = _copy_asset_for_project(
                support.audio_path,
                project_path,
                _bucket_for_path(support.audio_path, "audio"),
            )
        for hotspot in list(getattr(scene, "hotspots", []) or []):
            hotspot.audio_path = _copy_asset_for_project(
                getattr(hotspot, "audio_path", ""),
                project_path,
                _bucket_for_path(getattr(hotspot, "audio_path", ""), "audio"),
            )


def _resolve_asset_path(value: str, project_path: str) -> str:
    value = (value or "").strip()
    if not value:
        return ""
    # Project JSON may contain Windows-style separators. Normalize them so
    # project files remain portable and assets can still be resolved if the
    # project is inspected or repaired on another platform.
    normalized = value.replace("\\", os.sep)
    path = Path(normalized)
    if path.is_absolute():
        return str(path)
    return str((Path(project_path).parent / path).resolve())


def _resolve_project_assets_after_load(project: StoryProject, project_path: str) -> None:
    for scene in project.scenes:
        scene.background_image = _resolve_asset_path(scene.background_image, project_path)
        scene.scene_audio = _resolve_asset_path(scene.scene_audio, project_path)
        for cell in scene.cells:
            cell.image_path = _resolve_asset_path(cell.image_path, project_path)
            cell.audio_path = _resolve_asset_path(cell.audio_path, project_path)
        for support in list(getattr(scene, "supports", []) or []):
            support.image_path = _resolve_asset_path(support.image_path, project_path)
            support.audio_path = _resolve_asset_path(support.audio_path, project_path)
        for hotspot in list(getattr(scene, "hotspots", []) or []):
            hotspot.audio_path = _resolve_asset_path(getattr(hotspot, "audio_path", ""), project_path)


def save_project(project: StoryProject, path: str) -> None:
    project.file_path = path
    # Normalize live data before serializing so recently edited hotspots/cells
    # are guaranteed to be part of the saved payload.
    from app.models import normalize_scene
    for scene in list(project.scenes or []):
        normalize_scene(scene, project.grid_rows, project.grid_cols)
    # Work on a detached copy so the in-memory project keeps absolute asset paths
    # required by the live Tkinter UI. Only the saved JSON should contain the
    # project-relative asset references.
    payload_project = StoryProject.from_dict(project.to_dict())
    payload_project.file_path = path
    _prepare_project_assets_for_save(payload_project, path)
    save_json(path, payload_project.to_dict())


def load_project(path: str) -> StoryProject:
    payload = load_json(path, {})
    project = StoryProject.from_dict(payload)
    project.file_path = path
    _resolve_project_assets_after_load(project, path)
    return project


def next_scene_index(project: StoryProject, current_index: int) -> int:
    return min(current_index + 1, len(project.scenes) - 1)


def previous_scene_index(current_index: int) -> int:
    return max(0, current_index - 1)


def infer_project_name_from_path(path: str) -> str:
    return os.path.splitext(os.path.basename(path))[0].upper()
